name: fatima-elmouhine

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Checkout repository
        run: docker build -t ghcr.io/fatima-elmouhine/fatima-elmouhine-docker:1.0.0 . --file Dockerfile --tag ghcr.io/fatima-elmouhine/fatima-elmouhine-docker:1.0.0 docker run -d -p 80:80 ghcr.io/fatima-elmouhine/fatima-elmouhine-docker:1.0.0      
